---
- name: Deploy Baseline Configuration to Network
  hosts: all
  connection: network_cli

  tasks:
    - name: Configure MOTD Banner
      ios_banner:
        banner: motd
        text: Welcome. This banner is managed by Ansible.
